interface ILiteralObject {
    [key: string]: string;
}

export const FOOTBALL_CLUBS = [
    { category: "kleague1", optionName: "FC서울", value: "seoul" },
    { category: "kleague1", optionName: "강원FC", value: "gangwon" },
    { category: "kleague1", optionName: "광주FC", value: "gwangju" },
    { category: "kleague1", optionName: "대구FC", value: "daegu" },
    { category: "kleague1", optionName: "대전하나시티즌", value: "daejeon" },
    { category: "kleague1", optionName: "수원삼성블루윙즈", value: "suwonbluewings" },
    { category: "kleague1", optionName: "수원FC", value: "suwonfc" },
    { category: "kleague1", optionName: "울산현대", value: "ulsan" },
    { category: "kleague1", optionName: "인천유나이티드", value: "incheon" },
    { category: "kleague1", optionName: "전북현대모터스", value: "jeonbuk" },
    { category: "kleague1", optionName: "제주유나이티드", value: "jeju" },
    { category: "kleague1", optionName: "포항스틸러스", value: "pohang" },
    { category: "kleague2", optionName: "경남FC", value: "gyeongnam" },
    { category: "kleague2", optionName: "김천상무", value: "sangmu" },
    { category: "kleague2", optionName: "김포FC", value: "gimpo" },
    { category: "kleague2", optionName: "부산아이파크", value: "busan" },
    { category: "kleague2", optionName: "부천FC1995", value: "bucheon" },
    { category: "kleague2", optionName: "서울이랜드", value: "seouleland" },
    { category: "kleague2", optionName: "성남FC", value: "seongnam" },
    { category: "kleague2", optionName: "안산그리너스", value: "ansan" },
    { category: "kleague2", optionName: "FC안양", value: "anyang" },
    { category: "kleague2", optionName: "전남드래곤즈", value: "jeonnam" },
    { category: "kleague2", optionName: "아산FC", value: "asan" },
    { category: "kleague2", optionName: "청주FC", value: "cheongju" },
    { category: "kleague2", optionName: "천안시티FC", value: "cheonan" },
    { category: "epl", optionName: "노팅엄", value: "nottingham" },
    { category: "epl", optionName: "뉴캐슬", value: "newcastle" },
    { category: "epl", optionName: "루턴타운", value: "lutontown" },
    { category: "epl", optionName: "리버풀", value: "liverpool" },
    { category: "epl", optionName: "맨시티", value: "manchestercity" },
    { category: "epl", optionName: "맨체스터유나이티드", value: "manchesterutd" },
    { category: "epl", optionName: "번리", value: "burnley" },
    { category: "epl", optionName: "본머스", value: "afcbournemouth" },
    { category: "epl", optionName: "브라이튼", value: "brighton" },
    { category: "epl", optionName: "브렌트포드", value: "brentford" },
    { category: "epl", optionName: "세필드유나이티드", value: "sheffield" },
    { category: "epl", optionName: "아스날", value: "arsenal" },
    { category: "epl", optionName: "아스톤빌라", value: "astonvilla" },
    { category: "epl", optionName: "에버튼", value: "everton" },
    { category: "epl", optionName: "울버햄튼", value: "wolverhampton" },
    { category: "epl", optionName: "웨스트햄", value: "westham" },
    { category: "epl", optionName: "첼시", value: "chelsea" },
    { category: "epl", optionName: "크리스탈팰리스", value: "palace" },
    { category: "epl", optionName: "토트넘", value: "tottenham" },
    { category: "epl", optionName: "풀럼", value: "fulham" },
    { category: "frleague1", optionName: "파리생제르맹", value: "psg" },
    { category: "frleague1", optionName: "AS모나코", value: "asmonaco" },
    { category: "frleague1", optionName: "OGC니스", value: "ogcnice" },
    { category: "etc", optionName: "없음", value: "NOT_SELECTED" },
];

export const FOOTBALL_LEAGUE = [
    { optionName: "K리그1", value: "kleague1" },
    { optionName: "K리그2", value: "kleague2" },
    { optionName: "프리미어리그", value: "epl" },
    { optionName: "분데스리가", value: "bundesliga" },
    { optionName: "세리에A", value: "seriea" },
    { optionName: "프랑스리그앙", value: "frleague1" },
    { optionName: "기타", value: "etc" },
];
export const FOOTBALL_LEAGUE_KR: ILiteralObject = {
    kleague1: "K리그1",
    kleague2: "K리그2",
    epl: "프리미어리그",
    bundesliga: "분데스리가",
    seriea: "세리에A",
    frleague1: "프랑스리그앙",
    etc: "기타",
};
