export const BASIC_THEME = {
  main: "var(--main)",
  main2: "var(--main2)",
  sub1: "var(--sub1)",
  sub2: "var(--sub2)",
  gray1: "var(--gray1)",
  gray2: "var(--gray2)",
  gray3: "var(--gray3)",
  gray4: "var(--gray4)",
  placeholder: "var(--placeholder)",
  warn: "var(--warn)",
  white: "var(--white)",
  black: "var(--black)",
  text: "var(--text)",
  green: "var(--green)",
  background: "var(--background)",
};
