/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as UserIndexRouteImport } from './app/user/index'
import { Route as TeamCreateIndexRouteImport } from './app/team-create/index'
import { Route as RegisterIndexRouteImport } from './app/register/index'
import { Route as NotificationIndexRouteImport } from './app/notification/index'
import { Route as MyIndexRouteImport } from './app/my/index'
import { Route as MatchIndexRouteImport } from './app/match/index'
import { Route as HomeIndexRouteImport } from './app/home/index'
import { Route as FeedIndexRouteImport } from './app/feed/index'
import { Route as ControlIndexRouteImport } from './app/control/index'
import { Route as PcStaffRouteRouteImport } from './app/pc/staff/route'
import { Route as UserLogoutIndexRouteImport } from './app/user/logout/index'
import { Route as TeamFindIndexRouteImport } from './app/team/find/index'
import { Route as PcStaffIndexRouteImport } from './app/pc/staff/index'
import { Route as PUserIdIndexRouteImport } from './app/p/$userId/index'
import { Route as MyTeamListIndexRouteImport } from './app/my/team-list/index'
import { Route as MySportsIndexRouteImport } from './app/my/sports/index'
import { Route as MySchoolIndexRouteImport } from './app/my/school/index'
import { Route as MyPhysicalIndexRouteImport } from './app/my/physical/index'
import { Route as MyNotificationIndexRouteImport } from './app/my/notification/index'
import { Route as MyNoticeIndexRouteImport } from './app/my/notice/index'
import { Route as MyLocationIndexRouteImport } from './app/my/location/index'
import { Route as MyInfoIndexRouteImport } from './app/my/info/index'
import { Route as MyAccountIndexRouteImport } from './app/my/account/index'
import { Route as MatchMatchIdIndexRouteImport } from './app/match/$matchId/index'
import { Route as TeamTeamIdScheduleRouteRouteImport } from './app/team/$teamId/schedule/route'
import { Route as UserLoginTestIndexRouteImport } from './app/user/login/test/index'
import { Route as UserLoginKakaoIndexRouteImport } from './app/user/login/kakao/index'
import { Route as UserLoginGoogleIndexRouteImport } from './app/user/login/google/index'
import { Route as TeamTeamIdVideoIndexRouteImport } from './app/team/$teamId/video/index'
import { Route as TeamTeamIdStatisticsIndexRouteImport } from './app/team/$teamId/statistics/index'
import { Route as TeamTeamIdScheduleIndexRouteImport } from './app/team/$teamId/schedule/index'
import { Route as TeamTeamIdPlayersIndexRouteImport } from './app/team/$teamId/players/index'
import { Route as TeamTeamIdMatchesIndexRouteImport } from './app/team/$teamId/matches/index'
import { Route as TeamTeamIdBoardIndexRouteImport } from './app/team/$teamId/board/index'
import { Route as TeamTeamIdAdminIndexRouteImport } from './app/team/$teamId/admin/index'
import { Route as TeamTeamIdHomeIndexRouteImport } from './app/team/$teamId/_home/index'
import { Route as PcStaffCompetitionIndexRouteImport } from './app/pc/staff/competition/index'
import { Route as CompetitionCompetitionIdApplyIndexRouteImport } from './app/competition/$competitionId/apply/index'
import { Route as CompetitionCompetitionIdMainIndexRouteImport } from './app/competition/$competitionId/_main/index'
import { Route as TeamTeamIdVideoArticleIdIndexRouteImport } from './app/team/$teamId/video/$articleId/index'
import { Route as TeamTeamIdStatisticsRecordsIndexRouteImport } from './app/team/$teamId/statistics/records/index'
import { Route as TeamTeamIdStatisticsLeaderboardIndexRouteImport } from './app/team/$teamId/statistics/leaderboard/index'
import { Route as TeamTeamIdBoardEditorIndexRouteImport } from './app/team/$teamId/board/editor/index'
import { Route as TeamTeamIdBoardArticleIdIndexRouteImport } from './app/team/$teamId/board/$articleId/index'
import { Route as TeamTeamIdAdminRoleIndexRouteImport } from './app/team/$teamId/admin/role/index'
import { Route as TeamTeamIdAdminPlayerBatchIndexRouteImport } from './app/team/$teamId/admin/player-batch/index'
import { Route as TeamTeamIdAdminJoinRequestIndexRouteImport } from './app/team/$teamId/admin/join-request/index'
import { Route as TeamTeamIdAdminBlockIndexRouteImport } from './app/team/$teamId/admin/block/index'
import { Route as PcStaffCompetitionCreateIndexRouteImport } from './app/pc/staff/competition/create/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCreateIndexRoute = TeamCreateIndexRouteImport.update({
  id: '/team-create/',
  path: '/team-create/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationIndexRoute = NotificationIndexRouteImport.update({
  id: '/notification/',
  path: '/notification/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIndexRoute = MatchIndexRouteImport.update({
  id: '/match/',
  path: '/match/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/control/',
  path: '/control/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcStaffRouteRoute = PcStaffRouteRouteImport.update({
  id: '/pc/staff',
  path: '/pc/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLogoutIndexRoute = UserLogoutIndexRouteImport.update({
  id: '/user/logout/',
  path: '/user/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamFindIndexRoute = TeamFindIndexRouteImport.update({
  id: '/team/find/',
  path: '/team/find/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcStaffIndexRoute = PcStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PcStaffRouteRoute,
} as any)
const PUserIdIndexRoute = PUserIdIndexRouteImport.update({
  id: '/p/$userId/',
  path: '/p/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamListIndexRoute = MyTeamListIndexRouteImport.update({
  id: '/my/team-list/',
  path: '/my/team-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySportsIndexRoute = MySportsIndexRouteImport.update({
  id: '/my/sports/',
  path: '/my/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySchoolIndexRoute = MySchoolIndexRouteImport.update({
  id: '/my/school/',
  path: '/my/school/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPhysicalIndexRoute = MyPhysicalIndexRouteImport.update({
  id: '/my/physical/',
  path: '/my/physical/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNotificationIndexRoute = MyNotificationIndexRouteImport.update({
  id: '/my/notification/',
  path: '/my/notification/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNoticeIndexRoute = MyNoticeIndexRouteImport.update({
  id: '/my/notice/',
  path: '/my/notice/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLocationIndexRoute = MyLocationIndexRouteImport.update({
  id: '/my/location/',
  path: '/my/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInfoIndexRoute = MyInfoIndexRouteImport.update({
  id: '/my/info/',
  path: '/my/info/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountIndexRoute = MyAccountIndexRouteImport.update({
  id: '/my/account/',
  path: '/my/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdIndexRoute = MatchMatchIdIndexRouteImport.update({
  id: '/match/$matchId/',
  path: '/match/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdScheduleRouteRoute = TeamTeamIdScheduleRouteRouteImport.update({
  id: '/team/$teamId/schedule',
  path: '/team/$teamId/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginTestIndexRoute = UserLoginTestIndexRouteImport.update({
  id: '/user/login/test/',
  path: '/user/login/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginKakaoIndexRoute = UserLoginKakaoIndexRouteImport.update({
  id: '/user/login/kakao/',
  path: '/user/login/kakao/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginGoogleIndexRoute = UserLoginGoogleIndexRouteImport.update({
  id: '/user/login/google/',
  path: '/user/login/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdVideoIndexRoute = TeamTeamIdVideoIndexRouteImport.update({
  id: '/team/$teamId/video/',
  path: '/team/$teamId/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdStatisticsIndexRoute =
  TeamTeamIdStatisticsIndexRouteImport.update({
    id: '/team/$teamId/statistics/',
    path: '/team/$teamId/statistics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdScheduleIndexRoute = TeamTeamIdScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamTeamIdScheduleRouteRoute,
} as any)
const TeamTeamIdPlayersIndexRoute = TeamTeamIdPlayersIndexRouteImport.update({
  id: '/team/$teamId/players/',
  path: '/team/$teamId/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdMatchesIndexRoute = TeamTeamIdMatchesIndexRouteImport.update({
  id: '/team/$teamId/matches/',
  path: '/team/$teamId/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdBoardIndexRoute = TeamTeamIdBoardIndexRouteImport.update({
  id: '/team/$teamId/board/',
  path: '/team/$teamId/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdAdminIndexRoute = TeamTeamIdAdminIndexRouteImport.update({
  id: '/team/$teamId/admin/',
  path: '/team/$teamId/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdHomeIndexRoute = TeamTeamIdHomeIndexRouteImport.update({
  id: '/team/$teamId/_home/',
  path: '/team/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PcStaffCompetitionIndexRoute = PcStaffCompetitionIndexRouteImport.update({
  id: '/competition/',
  path: '/competition/',
  getParentRoute: () => PcStaffRouteRoute,
} as any)
const CompetitionCompetitionIdApplyIndexRoute =
  CompetitionCompetitionIdApplyIndexRouteImport.update({
    id: '/competition/$competitionId/apply/',
    path: '/competition/$competitionId/apply/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompetitionCompetitionIdMainIndexRoute =
  CompetitionCompetitionIdMainIndexRouteImport.update({
    id: '/competition/$competitionId/_main/',
    path: '/competition/$competitionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdVideoArticleIdIndexRoute =
  TeamTeamIdVideoArticleIdIndexRouteImport.update({
    id: '/team/$teamId/video/$articleId/',
    path: '/team/$teamId/video/$articleId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdStatisticsRecordsIndexRoute =
  TeamTeamIdStatisticsRecordsIndexRouteImport.update({
    id: '/team/$teamId/statistics/records/',
    path: '/team/$teamId/statistics/records/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdStatisticsLeaderboardIndexRoute =
  TeamTeamIdStatisticsLeaderboardIndexRouteImport.update({
    id: '/team/$teamId/statistics/leaderboard/',
    path: '/team/$teamId/statistics/leaderboard/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdBoardEditorIndexRoute =
  TeamTeamIdBoardEditorIndexRouteImport.update({
    id: '/team/$teamId/board/editor/',
    path: '/team/$teamId/board/editor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdBoardArticleIdIndexRoute =
  TeamTeamIdBoardArticleIdIndexRouteImport.update({
    id: '/team/$teamId/board/$articleId/',
    path: '/team/$teamId/board/$articleId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdAdminRoleIndexRoute =
  TeamTeamIdAdminRoleIndexRouteImport.update({
    id: '/team/$teamId/admin/role/',
    path: '/team/$teamId/admin/role/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdAdminPlayerBatchIndexRoute =
  TeamTeamIdAdminPlayerBatchIndexRouteImport.update({
    id: '/team/$teamId/admin/player-batch/',
    path: '/team/$teamId/admin/player-batch/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdAdminJoinRequestIndexRoute =
  TeamTeamIdAdminJoinRequestIndexRouteImport.update({
    id: '/team/$teamId/admin/join-request/',
    path: '/team/$teamId/admin/join-request/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdAdminBlockIndexRoute =
  TeamTeamIdAdminBlockIndexRouteImport.update({
    id: '/team/$teamId/admin/block/',
    path: '/team/$teamId/admin/block/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PcStaffCompetitionCreateIndexRoute =
  PcStaffCompetitionCreateIndexRouteImport.update({
    id: '/competition/create/',
    path: '/competition/create/',
    getParentRoute: () => PcStaffRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pc/staff': typeof PcStaffRouteRouteWithChildren
  '/control/': typeof ControlIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/home/': typeof HomeIndexRoute
  '/match/': typeof MatchIndexRoute
  '/my/': typeof MyIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/team-create/': typeof TeamCreateIndexRoute
  '/user/': typeof UserIndexRoute
  '/team/$teamId/schedule': typeof TeamTeamIdScheduleRouteRouteWithChildren
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
  '/my/account/': typeof MyAccountIndexRoute
  '/my/info/': typeof MyInfoIndexRoute
  '/my/location/': typeof MyLocationIndexRoute
  '/my/notice/': typeof MyNoticeIndexRoute
  '/my/notification/': typeof MyNotificationIndexRoute
  '/my/physical/': typeof MyPhysicalIndexRoute
  '/my/school/': typeof MySchoolIndexRoute
  '/my/sports/': typeof MySportsIndexRoute
  '/my/team-list/': typeof MyTeamListIndexRoute
  '/p/$userId/': typeof PUserIdIndexRoute
  '/pc/staff/': typeof PcStaffIndexRoute
  '/team/find/': typeof TeamFindIndexRoute
  '/user/logout/': typeof UserLogoutIndexRoute
  '/competition/$competitionId/': typeof CompetitionCompetitionIdMainIndexRoute
  '/competition/$competitionId/apply/': typeof CompetitionCompetitionIdApplyIndexRoute
  '/pc/staff/competition/': typeof PcStaffCompetitionIndexRoute
  '/team/$teamId/': typeof TeamTeamIdHomeIndexRoute
  '/team/$teamId/admin/': typeof TeamTeamIdAdminIndexRoute
  '/team/$teamId/board/': typeof TeamTeamIdBoardIndexRoute
  '/team/$teamId/matches/': typeof TeamTeamIdMatchesIndexRoute
  '/team/$teamId/players/': typeof TeamTeamIdPlayersIndexRoute
  '/team/$teamId/schedule/': typeof TeamTeamIdScheduleIndexRoute
  '/team/$teamId/statistics/': typeof TeamTeamIdStatisticsIndexRoute
  '/team/$teamId/video/': typeof TeamTeamIdVideoIndexRoute
  '/user/login/google/': typeof UserLoginGoogleIndexRoute
  '/user/login/kakao/': typeof UserLoginKakaoIndexRoute
  '/user/login/test/': typeof UserLoginTestIndexRoute
  '/pc/staff/competition/create/': typeof PcStaffCompetitionCreateIndexRoute
  '/team/$teamId/admin/block/': typeof TeamTeamIdAdminBlockIndexRoute
  '/team/$teamId/admin/join-request/': typeof TeamTeamIdAdminJoinRequestIndexRoute
  '/team/$teamId/admin/player-batch/': typeof TeamTeamIdAdminPlayerBatchIndexRoute
  '/team/$teamId/admin/role/': typeof TeamTeamIdAdminRoleIndexRoute
  '/team/$teamId/board/$articleId/': typeof TeamTeamIdBoardArticleIdIndexRoute
  '/team/$teamId/board/editor/': typeof TeamTeamIdBoardEditorIndexRoute
  '/team/$teamId/statistics/leaderboard/': typeof TeamTeamIdStatisticsLeaderboardIndexRoute
  '/team/$teamId/statistics/records/': typeof TeamTeamIdStatisticsRecordsIndexRoute
  '/team/$teamId/video/$articleId/': typeof TeamTeamIdVideoArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlIndexRoute
  '/feed': typeof FeedIndexRoute
  '/home': typeof HomeIndexRoute
  '/match': typeof MatchIndexRoute
  '/my': typeof MyIndexRoute
  '/notification': typeof NotificationIndexRoute
  '/register': typeof RegisterIndexRoute
  '/team-create': typeof TeamCreateIndexRoute
  '/user': typeof UserIndexRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
  '/my/account': typeof MyAccountIndexRoute
  '/my/info': typeof MyInfoIndexRoute
  '/my/location': typeof MyLocationIndexRoute
  '/my/notice': typeof MyNoticeIndexRoute
  '/my/notification': typeof MyNotificationIndexRoute
  '/my/physical': typeof MyPhysicalIndexRoute
  '/my/school': typeof MySchoolIndexRoute
  '/my/sports': typeof MySportsIndexRoute
  '/my/team-list': typeof MyTeamListIndexRoute
  '/p/$userId': typeof PUserIdIndexRoute
  '/pc/staff': typeof PcStaffIndexRoute
  '/team/find': typeof TeamFindIndexRoute
  '/user/logout': typeof UserLogoutIndexRoute
  '/competition/$competitionId': typeof CompetitionCompetitionIdMainIndexRoute
  '/competition/$competitionId/apply': typeof CompetitionCompetitionIdApplyIndexRoute
  '/pc/staff/competition': typeof PcStaffCompetitionIndexRoute
  '/team/$teamId': typeof TeamTeamIdHomeIndexRoute
  '/team/$teamId/admin': typeof TeamTeamIdAdminIndexRoute
  '/team/$teamId/board': typeof TeamTeamIdBoardIndexRoute
  '/team/$teamId/matches': typeof TeamTeamIdMatchesIndexRoute
  '/team/$teamId/players': typeof TeamTeamIdPlayersIndexRoute
  '/team/$teamId/schedule': typeof TeamTeamIdScheduleIndexRoute
  '/team/$teamId/statistics': typeof TeamTeamIdStatisticsIndexRoute
  '/team/$teamId/video': typeof TeamTeamIdVideoIndexRoute
  '/user/login/google': typeof UserLoginGoogleIndexRoute
  '/user/login/kakao': typeof UserLoginKakaoIndexRoute
  '/user/login/test': typeof UserLoginTestIndexRoute
  '/pc/staff/competition/create': typeof PcStaffCompetitionCreateIndexRoute
  '/team/$teamId/admin/block': typeof TeamTeamIdAdminBlockIndexRoute
  '/team/$teamId/admin/join-request': typeof TeamTeamIdAdminJoinRequestIndexRoute
  '/team/$teamId/admin/player-batch': typeof TeamTeamIdAdminPlayerBatchIndexRoute
  '/team/$teamId/admin/role': typeof TeamTeamIdAdminRoleIndexRoute
  '/team/$teamId/board/$articleId': typeof TeamTeamIdBoardArticleIdIndexRoute
  '/team/$teamId/board/editor': typeof TeamTeamIdBoardEditorIndexRoute
  '/team/$teamId/statistics/leaderboard': typeof TeamTeamIdStatisticsLeaderboardIndexRoute
  '/team/$teamId/statistics/records': typeof TeamTeamIdStatisticsRecordsIndexRoute
  '/team/$teamId/video/$articleId': typeof TeamTeamIdVideoArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pc/staff': typeof PcStaffRouteRouteWithChildren
  '/control/': typeof ControlIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/home/': typeof HomeIndexRoute
  '/match/': typeof MatchIndexRoute
  '/my/': typeof MyIndexRoute
  '/notification/': typeof NotificationIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/team-create/': typeof TeamCreateIndexRoute
  '/user/': typeof UserIndexRoute
  '/team/$teamId/schedule': typeof TeamTeamIdScheduleRouteRouteWithChildren
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
  '/my/account/': typeof MyAccountIndexRoute
  '/my/info/': typeof MyInfoIndexRoute
  '/my/location/': typeof MyLocationIndexRoute
  '/my/notice/': typeof MyNoticeIndexRoute
  '/my/notification/': typeof MyNotificationIndexRoute
  '/my/physical/': typeof MyPhysicalIndexRoute
  '/my/school/': typeof MySchoolIndexRoute
  '/my/sports/': typeof MySportsIndexRoute
  '/my/team-list/': typeof MyTeamListIndexRoute
  '/p/$userId/': typeof PUserIdIndexRoute
  '/pc/staff/': typeof PcStaffIndexRoute
  '/team/find/': typeof TeamFindIndexRoute
  '/user/logout/': typeof UserLogoutIndexRoute
  '/competition/$competitionId/_main/': typeof CompetitionCompetitionIdMainIndexRoute
  '/competition/$competitionId/apply/': typeof CompetitionCompetitionIdApplyIndexRoute
  '/pc/staff/competition/': typeof PcStaffCompetitionIndexRoute
  '/team/$teamId/_home/': typeof TeamTeamIdHomeIndexRoute
  '/team/$teamId/admin/': typeof TeamTeamIdAdminIndexRoute
  '/team/$teamId/board/': typeof TeamTeamIdBoardIndexRoute
  '/team/$teamId/matches/': typeof TeamTeamIdMatchesIndexRoute
  '/team/$teamId/players/': typeof TeamTeamIdPlayersIndexRoute
  '/team/$teamId/schedule/': typeof TeamTeamIdScheduleIndexRoute
  '/team/$teamId/statistics/': typeof TeamTeamIdStatisticsIndexRoute
  '/team/$teamId/video/': typeof TeamTeamIdVideoIndexRoute
  '/user/login/google/': typeof UserLoginGoogleIndexRoute
  '/user/login/kakao/': typeof UserLoginKakaoIndexRoute
  '/user/login/test/': typeof UserLoginTestIndexRoute
  '/pc/staff/competition/create/': typeof PcStaffCompetitionCreateIndexRoute
  '/team/$teamId/admin/block/': typeof TeamTeamIdAdminBlockIndexRoute
  '/team/$teamId/admin/join-request/': typeof TeamTeamIdAdminJoinRequestIndexRoute
  '/team/$teamId/admin/player-batch/': typeof TeamTeamIdAdminPlayerBatchIndexRoute
  '/team/$teamId/admin/role/': typeof TeamTeamIdAdminRoleIndexRoute
  '/team/$teamId/board/$articleId/': typeof TeamTeamIdBoardArticleIdIndexRoute
  '/team/$teamId/board/editor/': typeof TeamTeamIdBoardEditorIndexRoute
  '/team/$teamId/statistics/leaderboard/': typeof TeamTeamIdStatisticsLeaderboardIndexRoute
  '/team/$teamId/statistics/records/': typeof TeamTeamIdStatisticsRecordsIndexRoute
  '/team/$teamId/video/$articleId/': typeof TeamTeamIdVideoArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pc/staff'
    | '/control/'
    | '/feed/'
    | '/home/'
    | '/match/'
    | '/my/'
    | '/notification/'
    | '/register/'
    | '/team-create/'
    | '/user/'
    | '/team/$teamId/schedule'
    | '/match/$matchId/'
    | '/my/account/'
    | '/my/info/'
    | '/my/location/'
    | '/my/notice/'
    | '/my/notification/'
    | '/my/physical/'
    | '/my/school/'
    | '/my/sports/'
    | '/my/team-list/'
    | '/p/$userId/'
    | '/pc/staff/'
    | '/team/find/'
    | '/user/logout/'
    | '/competition/$competitionId/'
    | '/competition/$competitionId/apply/'
    | '/pc/staff/competition/'
    | '/team/$teamId/'
    | '/team/$teamId/admin/'
    | '/team/$teamId/board/'
    | '/team/$teamId/matches/'
    | '/team/$teamId/players/'
    | '/team/$teamId/schedule/'
    | '/team/$teamId/statistics/'
    | '/team/$teamId/video/'
    | '/user/login/google/'
    | '/user/login/kakao/'
    | '/user/login/test/'
    | '/pc/staff/competition/create/'
    | '/team/$teamId/admin/block/'
    | '/team/$teamId/admin/join-request/'
    | '/team/$teamId/admin/player-batch/'
    | '/team/$teamId/admin/role/'
    | '/team/$teamId/board/$articleId/'
    | '/team/$teamId/board/editor/'
    | '/team/$teamId/statistics/leaderboard/'
    | '/team/$teamId/statistics/records/'
    | '/team/$teamId/video/$articleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/feed'
    | '/home'
    | '/match'
    | '/my'
    | '/notification'
    | '/register'
    | '/team-create'
    | '/user'
    | '/match/$matchId'
    | '/my/account'
    | '/my/info'
    | '/my/location'
    | '/my/notice'
    | '/my/notification'
    | '/my/physical'
    | '/my/school'
    | '/my/sports'
    | '/my/team-list'
    | '/p/$userId'
    | '/pc/staff'
    | '/team/find'
    | '/user/logout'
    | '/competition/$competitionId'
    | '/competition/$competitionId/apply'
    | '/pc/staff/competition'
    | '/team/$teamId'
    | '/team/$teamId/admin'
    | '/team/$teamId/board'
    | '/team/$teamId/matches'
    | '/team/$teamId/players'
    | '/team/$teamId/schedule'
    | '/team/$teamId/statistics'
    | '/team/$teamId/video'
    | '/user/login/google'
    | '/user/login/kakao'
    | '/user/login/test'
    | '/pc/staff/competition/create'
    | '/team/$teamId/admin/block'
    | '/team/$teamId/admin/join-request'
    | '/team/$teamId/admin/player-batch'
    | '/team/$teamId/admin/role'
    | '/team/$teamId/board/$articleId'
    | '/team/$teamId/board/editor'
    | '/team/$teamId/statistics/leaderboard'
    | '/team/$teamId/statistics/records'
    | '/team/$teamId/video/$articleId'
  id:
    | '__root__'
    | '/'
    | '/pc/staff'
    | '/control/'
    | '/feed/'
    | '/home/'
    | '/match/'
    | '/my/'
    | '/notification/'
    | '/register/'
    | '/team-create/'
    | '/user/'
    | '/team/$teamId/schedule'
    | '/match/$matchId/'
    | '/my/account/'
    | '/my/info/'
    | '/my/location/'
    | '/my/notice/'
    | '/my/notification/'
    | '/my/physical/'
    | '/my/school/'
    | '/my/sports/'
    | '/my/team-list/'
    | '/p/$userId/'
    | '/pc/staff/'
    | '/team/find/'
    | '/user/logout/'
    | '/competition/$competitionId/_main/'
    | '/competition/$competitionId/apply/'
    | '/pc/staff/competition/'
    | '/team/$teamId/_home/'
    | '/team/$teamId/admin/'
    | '/team/$teamId/board/'
    | '/team/$teamId/matches/'
    | '/team/$teamId/players/'
    | '/team/$teamId/schedule/'
    | '/team/$teamId/statistics/'
    | '/team/$teamId/video/'
    | '/user/login/google/'
    | '/user/login/kakao/'
    | '/user/login/test/'
    | '/pc/staff/competition/create/'
    | '/team/$teamId/admin/block/'
    | '/team/$teamId/admin/join-request/'
    | '/team/$teamId/admin/player-batch/'
    | '/team/$teamId/admin/role/'
    | '/team/$teamId/board/$articleId/'
    | '/team/$teamId/board/editor/'
    | '/team/$teamId/statistics/leaderboard/'
    | '/team/$teamId/statistics/records/'
    | '/team/$teamId/video/$articleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PcStaffRouteRoute: typeof PcStaffRouteRouteWithChildren
  ControlIndexRoute: typeof ControlIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MatchIndexRoute: typeof MatchIndexRoute
  MyIndexRoute: typeof MyIndexRoute
  NotificationIndexRoute: typeof NotificationIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  TeamCreateIndexRoute: typeof TeamCreateIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  TeamTeamIdScheduleRouteRoute: typeof TeamTeamIdScheduleRouteRouteWithChildren
  MatchMatchIdIndexRoute: typeof MatchMatchIdIndexRoute
  MyAccountIndexRoute: typeof MyAccountIndexRoute
  MyInfoIndexRoute: typeof MyInfoIndexRoute
  MyLocationIndexRoute: typeof MyLocationIndexRoute
  MyNoticeIndexRoute: typeof MyNoticeIndexRoute
  MyNotificationIndexRoute: typeof MyNotificationIndexRoute
  MyPhysicalIndexRoute: typeof MyPhysicalIndexRoute
  MySchoolIndexRoute: typeof MySchoolIndexRoute
  MySportsIndexRoute: typeof MySportsIndexRoute
  MyTeamListIndexRoute: typeof MyTeamListIndexRoute
  PUserIdIndexRoute: typeof PUserIdIndexRoute
  TeamFindIndexRoute: typeof TeamFindIndexRoute
  UserLogoutIndexRoute: typeof UserLogoutIndexRoute
  CompetitionCompetitionIdMainIndexRoute: typeof CompetitionCompetitionIdMainIndexRoute
  CompetitionCompetitionIdApplyIndexRoute: typeof CompetitionCompetitionIdApplyIndexRoute
  TeamTeamIdHomeIndexRoute: typeof TeamTeamIdHomeIndexRoute
  TeamTeamIdAdminIndexRoute: typeof TeamTeamIdAdminIndexRoute
  TeamTeamIdBoardIndexRoute: typeof TeamTeamIdBoardIndexRoute
  TeamTeamIdMatchesIndexRoute: typeof TeamTeamIdMatchesIndexRoute
  TeamTeamIdPlayersIndexRoute: typeof TeamTeamIdPlayersIndexRoute
  TeamTeamIdStatisticsIndexRoute: typeof TeamTeamIdStatisticsIndexRoute
  TeamTeamIdVideoIndexRoute: typeof TeamTeamIdVideoIndexRoute
  UserLoginGoogleIndexRoute: typeof UserLoginGoogleIndexRoute
  UserLoginKakaoIndexRoute: typeof UserLoginKakaoIndexRoute
  UserLoginTestIndexRoute: typeof UserLoginTestIndexRoute
  TeamTeamIdAdminBlockIndexRoute: typeof TeamTeamIdAdminBlockIndexRoute
  TeamTeamIdAdminJoinRequestIndexRoute: typeof TeamTeamIdAdminJoinRequestIndexRoute
  TeamTeamIdAdminPlayerBatchIndexRoute: typeof TeamTeamIdAdminPlayerBatchIndexRoute
  TeamTeamIdAdminRoleIndexRoute: typeof TeamTeamIdAdminRoleIndexRoute
  TeamTeamIdBoardArticleIdIndexRoute: typeof TeamTeamIdBoardArticleIdIndexRoute
  TeamTeamIdBoardEditorIndexRoute: typeof TeamTeamIdBoardEditorIndexRoute
  TeamTeamIdStatisticsLeaderboardIndexRoute: typeof TeamTeamIdStatisticsLeaderboardIndexRoute
  TeamTeamIdStatisticsRecordsIndexRoute: typeof TeamTeamIdStatisticsRecordsIndexRoute
  TeamTeamIdVideoArticleIdIndexRoute: typeof TeamTeamIdVideoArticleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-create/': {
      id: '/team-create/'
      path: '/team-create'
      fullPath: '/team-create/'
      preLoaderRoute: typeof TeamCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification/': {
      id: '/notification/'
      path: '/notification'
      fullPath: '/notification/'
      preLoaderRoute: typeof NotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/': {
      id: '/match/'
      path: '/match'
      fullPath: '/match/'
      preLoaderRoute: typeof MatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/': {
      id: '/control/'
      path: '/control'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/staff': {
      id: '/pc/staff'
      path: '/pc/staff'
      fullPath: '/pc/staff'
      preLoaderRoute: typeof PcStaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/logout/': {
      id: '/user/logout/'
      path: '/user/logout'
      fullPath: '/user/logout/'
      preLoaderRoute: typeof UserLogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/find/': {
      id: '/team/find/'
      path: '/team/find'
      fullPath: '/team/find/'
      preLoaderRoute: typeof TeamFindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/staff/': {
      id: '/pc/staff/'
      path: '/'
      fullPath: '/pc/staff/'
      preLoaderRoute: typeof PcStaffIndexRouteImport
      parentRoute: typeof PcStaffRouteRoute
    }
    '/p/$userId/': {
      id: '/p/$userId/'
      path: '/p/$userId'
      fullPath: '/p/$userId/'
      preLoaderRoute: typeof PUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/team-list/': {
      id: '/my/team-list/'
      path: '/my/team-list'
      fullPath: '/my/team-list/'
      preLoaderRoute: typeof MyTeamListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/sports/': {
      id: '/my/sports/'
      path: '/my/sports'
      fullPath: '/my/sports/'
      preLoaderRoute: typeof MySportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/school/': {
      id: '/my/school/'
      path: '/my/school'
      fullPath: '/my/school/'
      preLoaderRoute: typeof MySchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/physical/': {
      id: '/my/physical/'
      path: '/my/physical'
      fullPath: '/my/physical/'
      preLoaderRoute: typeof MyPhysicalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/notification/': {
      id: '/my/notification/'
      path: '/my/notification'
      fullPath: '/my/notification/'
      preLoaderRoute: typeof MyNotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/notice/': {
      id: '/my/notice/'
      path: '/my/notice'
      fullPath: '/my/notice/'
      preLoaderRoute: typeof MyNoticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/location/': {
      id: '/my/location/'
      path: '/my/location'
      fullPath: '/my/location/'
      preLoaderRoute: typeof MyLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/info/': {
      id: '/my/info/'
      path: '/my/info'
      fullPath: '/my/info/'
      preLoaderRoute: typeof MyInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/account/': {
      id: '/my/account/'
      path: '/my/account'
      fullPath: '/my/account/'
      preLoaderRoute: typeof MyAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/': {
      id: '/match/$matchId/'
      path: '/match/$matchId'
      fullPath: '/match/$matchId/'
      preLoaderRoute: typeof MatchMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/schedule': {
      id: '/team/$teamId/schedule'
      path: '/team/$teamId/schedule'
      fullPath: '/team/$teamId/schedule'
      preLoaderRoute: typeof TeamTeamIdScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login/test/': {
      id: '/user/login/test/'
      path: '/user/login/test'
      fullPath: '/user/login/test/'
      preLoaderRoute: typeof UserLoginTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login/kakao/': {
      id: '/user/login/kakao/'
      path: '/user/login/kakao'
      fullPath: '/user/login/kakao/'
      preLoaderRoute: typeof UserLoginKakaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login/google/': {
      id: '/user/login/google/'
      path: '/user/login/google'
      fullPath: '/user/login/google/'
      preLoaderRoute: typeof UserLoginGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/video/': {
      id: '/team/$teamId/video/'
      path: '/team/$teamId/video'
      fullPath: '/team/$teamId/video/'
      preLoaderRoute: typeof TeamTeamIdVideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/statistics/': {
      id: '/team/$teamId/statistics/'
      path: '/team/$teamId/statistics'
      fullPath: '/team/$teamId/statistics/'
      preLoaderRoute: typeof TeamTeamIdStatisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/schedule/': {
      id: '/team/$teamId/schedule/'
      path: '/'
      fullPath: '/team/$teamId/schedule/'
      preLoaderRoute: typeof TeamTeamIdScheduleIndexRouteImport
      parentRoute: typeof TeamTeamIdScheduleRouteRoute
    }
    '/team/$teamId/players/': {
      id: '/team/$teamId/players/'
      path: '/team/$teamId/players'
      fullPath: '/team/$teamId/players/'
      preLoaderRoute: typeof TeamTeamIdPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/matches/': {
      id: '/team/$teamId/matches/'
      path: '/team/$teamId/matches'
      fullPath: '/team/$teamId/matches/'
      preLoaderRoute: typeof TeamTeamIdMatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/board/': {
      id: '/team/$teamId/board/'
      path: '/team/$teamId/board'
      fullPath: '/team/$teamId/board/'
      preLoaderRoute: typeof TeamTeamIdBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/admin/': {
      id: '/team/$teamId/admin/'
      path: '/team/$teamId/admin'
      fullPath: '/team/$teamId/admin/'
      preLoaderRoute: typeof TeamTeamIdAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/_home/': {
      id: '/team/$teamId/_home/'
      path: '/team/$teamId'
      fullPath: '/team/$teamId/'
      preLoaderRoute: typeof TeamTeamIdHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/staff/competition/': {
      id: '/pc/staff/competition/'
      path: '/competition'
      fullPath: '/pc/staff/competition/'
      preLoaderRoute: typeof PcStaffCompetitionIndexRouteImport
      parentRoute: typeof PcStaffRouteRoute
    }
    '/competition/$competitionId/apply/': {
      id: '/competition/$competitionId/apply/'
      path: '/competition/$competitionId/apply'
      fullPath: '/competition/$competitionId/apply/'
      preLoaderRoute: typeof CompetitionCompetitionIdApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/$competitionId/_main/': {
      id: '/competition/$competitionId/_main/'
      path: '/competition/$competitionId'
      fullPath: '/competition/$competitionId/'
      preLoaderRoute: typeof CompetitionCompetitionIdMainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/video/$articleId/': {
      id: '/team/$teamId/video/$articleId/'
      path: '/team/$teamId/video/$articleId'
      fullPath: '/team/$teamId/video/$articleId/'
      preLoaderRoute: typeof TeamTeamIdVideoArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/statistics/records/': {
      id: '/team/$teamId/statistics/records/'
      path: '/team/$teamId/statistics/records'
      fullPath: '/team/$teamId/statistics/records/'
      preLoaderRoute: typeof TeamTeamIdStatisticsRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/statistics/leaderboard/': {
      id: '/team/$teamId/statistics/leaderboard/'
      path: '/team/$teamId/statistics/leaderboard'
      fullPath: '/team/$teamId/statistics/leaderboard/'
      preLoaderRoute: typeof TeamTeamIdStatisticsLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/board/editor/': {
      id: '/team/$teamId/board/editor/'
      path: '/team/$teamId/board/editor'
      fullPath: '/team/$teamId/board/editor/'
      preLoaderRoute: typeof TeamTeamIdBoardEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/board/$articleId/': {
      id: '/team/$teamId/board/$articleId/'
      path: '/team/$teamId/board/$articleId'
      fullPath: '/team/$teamId/board/$articleId/'
      preLoaderRoute: typeof TeamTeamIdBoardArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/admin/role/': {
      id: '/team/$teamId/admin/role/'
      path: '/team/$teamId/admin/role'
      fullPath: '/team/$teamId/admin/role/'
      preLoaderRoute: typeof TeamTeamIdAdminRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/admin/player-batch/': {
      id: '/team/$teamId/admin/player-batch/'
      path: '/team/$teamId/admin/player-batch'
      fullPath: '/team/$teamId/admin/player-batch/'
      preLoaderRoute: typeof TeamTeamIdAdminPlayerBatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/admin/join-request/': {
      id: '/team/$teamId/admin/join-request/'
      path: '/team/$teamId/admin/join-request'
      fullPath: '/team/$teamId/admin/join-request/'
      preLoaderRoute: typeof TeamTeamIdAdminJoinRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/admin/block/': {
      id: '/team/$teamId/admin/block/'
      path: '/team/$teamId/admin/block'
      fullPath: '/team/$teamId/admin/block/'
      preLoaderRoute: typeof TeamTeamIdAdminBlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc/staff/competition/create/': {
      id: '/pc/staff/competition/create/'
      path: '/competition/create'
      fullPath: '/pc/staff/competition/create/'
      preLoaderRoute: typeof PcStaffCompetitionCreateIndexRouteImport
      parentRoute: typeof PcStaffRouteRoute
    }
  }
}

interface PcStaffRouteRouteChildren {
  PcStaffIndexRoute: typeof PcStaffIndexRoute
  PcStaffCompetitionIndexRoute: typeof PcStaffCompetitionIndexRoute
  PcStaffCompetitionCreateIndexRoute: typeof PcStaffCompetitionCreateIndexRoute
}

const PcStaffRouteRouteChildren: PcStaffRouteRouteChildren = {
  PcStaffIndexRoute: PcStaffIndexRoute,
  PcStaffCompetitionIndexRoute: PcStaffCompetitionIndexRoute,
  PcStaffCompetitionCreateIndexRoute: PcStaffCompetitionCreateIndexRoute,
}

const PcStaffRouteRouteWithChildren = PcStaffRouteRoute._addFileChildren(
  PcStaffRouteRouteChildren,
)

interface TeamTeamIdScheduleRouteRouteChildren {
  TeamTeamIdScheduleIndexRoute: typeof TeamTeamIdScheduleIndexRoute
}

const TeamTeamIdScheduleRouteRouteChildren: TeamTeamIdScheduleRouteRouteChildren =
  {
    TeamTeamIdScheduleIndexRoute: TeamTeamIdScheduleIndexRoute,
  }

const TeamTeamIdScheduleRouteRouteWithChildren =
  TeamTeamIdScheduleRouteRoute._addFileChildren(
    TeamTeamIdScheduleRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PcStaffRouteRoute: PcStaffRouteRouteWithChildren,
  ControlIndexRoute: ControlIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MatchIndexRoute: MatchIndexRoute,
  MyIndexRoute: MyIndexRoute,
  NotificationIndexRoute: NotificationIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  TeamCreateIndexRoute: TeamCreateIndexRoute,
  UserIndexRoute: UserIndexRoute,
  TeamTeamIdScheduleRouteRoute: TeamTeamIdScheduleRouteRouteWithChildren,
  MatchMatchIdIndexRoute: MatchMatchIdIndexRoute,
  MyAccountIndexRoute: MyAccountIndexRoute,
  MyInfoIndexRoute: MyInfoIndexRoute,
  MyLocationIndexRoute: MyLocationIndexRoute,
  MyNoticeIndexRoute: MyNoticeIndexRoute,
  MyNotificationIndexRoute: MyNotificationIndexRoute,
  MyPhysicalIndexRoute: MyPhysicalIndexRoute,
  MySchoolIndexRoute: MySchoolIndexRoute,
  MySportsIndexRoute: MySportsIndexRoute,
  MyTeamListIndexRoute: MyTeamListIndexRoute,
  PUserIdIndexRoute: PUserIdIndexRoute,
  TeamFindIndexRoute: TeamFindIndexRoute,
  UserLogoutIndexRoute: UserLogoutIndexRoute,
  CompetitionCompetitionIdMainIndexRoute:
    CompetitionCompetitionIdMainIndexRoute,
  CompetitionCompetitionIdApplyIndexRoute:
    CompetitionCompetitionIdApplyIndexRoute,
  TeamTeamIdHomeIndexRoute: TeamTeamIdHomeIndexRoute,
  TeamTeamIdAdminIndexRoute: TeamTeamIdAdminIndexRoute,
  TeamTeamIdBoardIndexRoute: TeamTeamIdBoardIndexRoute,
  TeamTeamIdMatchesIndexRoute: TeamTeamIdMatchesIndexRoute,
  TeamTeamIdPlayersIndexRoute: TeamTeamIdPlayersIndexRoute,
  TeamTeamIdStatisticsIndexRoute: TeamTeamIdStatisticsIndexRoute,
  TeamTeamIdVideoIndexRoute: TeamTeamIdVideoIndexRoute,
  UserLoginGoogleIndexRoute: UserLoginGoogleIndexRoute,
  UserLoginKakaoIndexRoute: UserLoginKakaoIndexRoute,
  UserLoginTestIndexRoute: UserLoginTestIndexRoute,
  TeamTeamIdAdminBlockIndexRoute: TeamTeamIdAdminBlockIndexRoute,
  TeamTeamIdAdminJoinRequestIndexRoute: TeamTeamIdAdminJoinRequestIndexRoute,
  TeamTeamIdAdminPlayerBatchIndexRoute: TeamTeamIdAdminPlayerBatchIndexRoute,
  TeamTeamIdAdminRoleIndexRoute: TeamTeamIdAdminRoleIndexRoute,
  TeamTeamIdBoardArticleIdIndexRoute: TeamTeamIdBoardArticleIdIndexRoute,
  TeamTeamIdBoardEditorIndexRoute: TeamTeamIdBoardEditorIndexRoute,
  TeamTeamIdStatisticsLeaderboardIndexRoute:
    TeamTeamIdStatisticsLeaderboardIndexRoute,
  TeamTeamIdStatisticsRecordsIndexRoute: TeamTeamIdStatisticsRecordsIndexRoute,
  TeamTeamIdVideoArticleIdIndexRoute: TeamTeamIdVideoArticleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
